// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl1r72sbYnRRdxnCy0WGkgxMHASrPODpA',
    appId: '1:192523687674:web:e833bc844ad421957b9b43',
    messagingSenderId: '192523687674',
    projectId: 'cookingapp-d3b1e',
    authDomain: 'cookingapp-d3b1e.firebaseapp.com',
    storageBucket: 'cookingapp-d3b1e.firebasestorage.app',
    measurementId: 'G-RQTJMETYX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoENscQgsYayoejCFpzlNsK_Ng6-2dkE0',
    appId: '1:192523687674:android:c34ea8e328a9ab547b9b43',
    messagingSenderId: '192523687674',
    projectId: 'cookingapp-d3b1e',
    storageBucket: 'cookingapp-d3b1e.firebasestorage.app',
  );
}
