name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Chỉ deploy khi push lên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create .env files
        run: |
          # Tạo file .env ở thư mục gốc
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
          # Tạo file .env ở thư mục assets
          mkdir -p assets
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > assets/.env

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - name: Build Flutter Web
        run: flutter build web --release --base-href="/HCMUS-Mobile-Final/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
