name: Build Flutter APK with Java 17

on:
  push:
    branches:
      - main # Chỉ chạy khi push lên nhánh main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create .env files
        run: |
          # Tạo file .env ở thư mục gốc
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
          # Tạo file .env ở thư mục assets
          mkdir -p assets
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > assets/.env

      # 2. Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Hoặc 'zulu', tùy ý

      # 3. Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1' # Hoặc chỉ định phiên bản cụ thể

      # 4. Ensure dependencies are resolved
      - name: Get Flutter dependencies
        run: flutter pub get

      # 5. Build the APK
      - name: Build APK
        run: flutter build apk

      # 6. Upload the APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
